#pragma once
const char* mandelbrot_fs = "#version 330\n"
"#define iterations 1000.0\n"
"#define PI 3.141592654\n"
"#define ESCAPE_RADIUS 70\n"
"// Input texture coords\n"
"in vec2 fragTexCoord;\n"
"\n"
"// Uniforms\n"
"uniform vec2 point;\n"
"uniform int mouse_buttons;\n"
"uniform int julia_toggle;\n"
"\n"
"// Output color\n"
"out vec4 finalColor;\n"
"\n"
"// Complex functions\n"
"#define cx_mul(a, b) vec2(a.x*b.x-a.y*b.y, a.x*b.y+a.y*b.x)\n"
"#define cx_div(a, b) vec2(((a.x*b.x+a.y*b.y)/(b.x*b.x+b.y*b.y)),((a.y*b.x-a.x*b.y)/(b.x*b.x+b.y*b.y)))\n"
"#define cx_modulus(a) length(a)\n"
"#define cx_conj(a) vec2(a.x, -a.y)\n"
"#define cx_arg(a) atan(a.y, a.x)\n"
"#define cx_sin(a) vec2(sin(a.x) * cosh(a.y), cos(a.x) * sinh(a.y))\n"
"#define cx_cos(a) vec2(cos(a.x) * cosh(a.y), -sin(a.x) * sinh(a.y))\n"
"#define cx_abs(a) vec2(abs(a.x),abs(a.y))\n"
"#define cx_exp(a) vec2(exp(a.x)*sin(a.y),exp(a.x)*cos(a.y))\n"
"\n"
"vec2 cx_sqrt(vec2 a) {\n"
"    float r = length(a);\n"
"    float rpart = sqrt(0.5*(r+a.x));\n"
"    float ipart = sqrt(0.5*(r-a.x));\n"
"    if (a.y < 0.0) ipart = -ipart;\n"
"    return vec2(rpart,ipart);\n"
"}\n"
"\n"
"vec2 cx_tan(vec2 a) {return cx_div(cx_sin(a), cx_cos(a)); }\n"
"\n"
"vec2 cx_log(vec2 a) {\n"
"    float rpart = sqrt((a.x*a.x)+(a.y*a.y));\n"
"    float ipart = atan(a.y,a.x);\n"
"    if (ipart > PI) ipart=ipart-(2.0*PI);\n"
"    return vec2(log(rpart),ipart);\n"
"}\n"
"\n"
"vec2 cx_mobius(vec2 a) {\n"
"    vec2 c1 = a - vec2(1.0,0.0);\n"
"    vec2 c2 = a + vec2(1.0,0.0);\n"
"    return cx_div(c1, c2);\n"
"}\n"
"\n"
"vec2 cx_z_plus_one_over_z(vec2 a) {\n"
"    return a + cx_div(vec2(1.0,0.0), a);\n"
"}\n"
"\n"
"vec2 cx_z_squared_plus_c(vec2 z, vec2 c) {\n"
"    return cx_mul(z, z) + c;\n"
"}\n"
"\n"
"vec2 cx_sin_of_one_over_z(vec2 z) {\n"
"    return cx_sin(cx_div(vec2(1.0,0.0), z));\n"
"}\n"
"\n"
"vec2 cx_square(vec2 z) {\n"
"    return vec2(z.x*z.x-z.y*z.y,2*z.x*z.y);\n"
"}\n"
"\n"
"\n"
"// Color conversion\n"
"vec3 hsv2rgb(vec3 c) {\n"
"    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);\n"
"    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);\n"
"    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);\n"
"}\n"
"\n"
"// Domain coloring\n"
"vec3 domainColoring (vec2 z) {\n"
"  float saturation = 0.9;\n"
"  float gridStrength = 0.5;\n"
"  float magStrength = 0.7;\n"
"  vec2 gridSpacing = vec2(1.0,1.0);\n"
"  float linePower = 8.0;\n"
"\n"
"  float carg = atan(z.y, z.x);\n"
"  float cmod = length(z);\n"
"\n"
"  float rebrt = (fract(z.x / gridSpacing.x) - 0.5) * 2.0;\n"
"  rebrt *= rebrt;\n"
"\n"
"  float imbrt = (fract(z.y / gridSpacing.y) - 0.5) * 2.0;\n"
"  imbrt *= imbrt;\n"
"\n"
"  float grid = 1.0 - (1.0 - rebrt) * (1.0 - imbrt);\n"
"  grid = pow(abs(grid), linePower);\n"
"\n"
"  float circ = (fract(log2(cmod)) - 0.5) * 2.0;\n"
"  circ = pow(abs(circ), linePower);\n"
"\n"
"  circ *= magStrength;\n"
"\n"
"  vec3 rgb = hsv2rgb(vec3(carg * 0.5 / PI, saturation, 0.5 + 0.5 * saturation - gridStrength * grid));\n"
"  rgb *= (1.0 - circ);\n"
"  rgb += circ * vec3(1.0);\n"
"  return rgb;\n"
"}\n"
"\n"
"vec4 mandelbrot(vec2 z, vec2 c) {\n"
"    int i;\n"
"    for(i = 0; i < iterations; i++) {\n"
"        if(length(z) > ESCAPE_RADIUS) break;\n"
"        z = cx_z_squared_plus_c(z,c);\n"
"    }\n"
"    return vec4(z,float(i),(i==iterations));\n"
"}\n"
"\n"
"float magic_formula(vec3 m) {\n"
"    return m.z + 1.0 - log(log(m.x * m.x + m.y * m.y) / 2.0 / log(2.0)) / log(2.0);\n"
"}\n"
"\n"
"vec3 palette(vec4 result) {\n"
"    if (result.w == 1.0) return vec3(0.0);\n"
"\n"
"    float t = magic_formula(result.xyz);\n"
"\n"
"    float hue = fract(t * 0.03);\n"
"    float sat = 0.85;\n"
"    float val = 1.0;\n"
"\n"
"    return hsv2rgb(vec3(hue, sat, val));\n"
"}\n"
"\n"
"\n"
"void main() {\n"
"    vec2 z = fragTexCoord;\n"
"\n"
"    vec4 m_result = mandelbrot(vec2(0.0), z);\n"
"    vec3 m_color = palette(m_result);\n"
"    vec4 j_result = mandelbrot(z,point);\n"
"    vec3 j_color = palette(j_result);\n"
"    if(julia_toggle == 1) {\n"
"        finalColor = vec4(j_color,1.0);\n"
"    }\n"
"    else if (mouse_buttons == 2) {\n"
"        finalColor = vec4(mix(j_color,m_color,0.5),1.0);\n"
"    }\n"
"    else {\n"
"        finalColor = vec4(m_color,1.0);\n"
"    }\n"
"}\n";